import {
  SiOpenjdk,
  SiSpringboot,
  SiSpringsecurity,
  SiReact,
  SiMysql,
  SiRedis,
  SiDocker,
  SiJunit5,
  SiGooglegemini,
  SiGithub,
  SiGithubactions,
  SiIntellijidea,
  SiAndroidstudio,
  SiSqlite,
  SiVite,
  SiApachemaven,
} from 'react-icons/si';
import { FaKey, FaBug } from 'react-icons/fa';
import { PROJECTS } from './Projects';
import '../styles/projects.css';

const TECH_ICONS = {
  java: SiOpenjdk,
  'spring boot': SiSpringboot,
  'spring security': SiSpringsecurity,
  react: SiReact,
  mysql: SiMysql,
  redis: SiRedis,
  docker: SiDocker,
  'junit 5': SiJunit5,
  junit: SiJunit5,
  mockito: FaBug,
  jwt: FaKey,
  oauth2: FaKey,
  'gemini api': SiGooglegemini,
  'github api': SiGithub,
  'github actions': SiGithubactions,
  intellijidea: SiIntellijidea,
  'android studio': SiAndroidstudio,
  sqlite: SiSqlite,
  vite: SiVite,
  maven: SiApachemaven,
};

const getTechIcon = (tag) => {
  const key = tag.toLowerCase().trim();
  if (TECH_ICONS[key]) return TECH_ICONS[key];
  if (key.startsWith('java')) return SiOpenjdk;
  if (key.startsWith('spring boot')) return SiSpringboot;
  if (key.startsWith('spring security')) return SiSpringsecurity;
  if (key.startsWith('react')) return SiReact;
  if (key.startsWith('junit')) return SiJunit5;
  if (key.startsWith('mockito')) return FaBug;
  return null;
};

const PR_REVIEWER = {
  id: 'pr-reviewer-ai',
  title: 'PR Reviewer AI',
  status: { type: 'recently-finished', es: 'Recién terminado', en: 'Recently finished' },
  description: {
    es: 'Analiza diffs de código (o pull requests completas de GitHub) y devuelve automáticamente una revisión de código estructurada, generada por un LLM (Gemini).',
    en: 'Analyzes code diffs (or full GitHub PRs) and returns a structured code review generated by an LLM (Gemini).',
  },
  tags: ['Java 21', 'Spring Boot', 'WebFlux', 'Gemini API', 'JUnit', 'Mockito', 'Maven'],
  repo: 'https://github.com/Jorge5115/pr-reviewer',
};

const GEAR_FIT_DESKTOP = {
  id: 'gear-fit-desktop',
  title: 'Gear Fit Desktop (TFG)',
  description: {
    es: 'Versión de escritorio de Gear Fit: aplicación JavaFX para gestionar nutrición, rutinas de entrenamiento y cuentas de usuario, desarrollada como proyecto de fin de grado (TFG) con persistencia en SQLite.',
    en: 'Desktop companion to Gear Fit: a JavaFX app to manage nutrition, workout routines and user accounts, built as my final degree project (TFG) with SQLite persistence.',
  },
  tags: ['Java', 'JavaFX', 'SQLite', 'Maven'],
  repo: 'https://github.com/Jorge5115/gearFit-desktop-TFG',
};

const byId = (id) => PROJECTS.find((project) => project.id === id);

const PROJECTS_LIST = [
  PR_REVIEWER,
  byId('notes-ai'),
  byId('stack-shop'),
  byId('invoice-manager'),
  byId('personal-notes'),
  byId('gear-fit'),
  GEAR_FIT_DESKTOP,
];

const ProjectsList = ({ language }) => (
  <section className="section" id="projects-list">
    <h2 className="section-title">{language === 'es' ? 'Proyectos' : 'Projects'}</h2>
    <div className="other-list">
      {PROJECTS_LIST.map((project) => {
        const title = typeof project.title === 'string' ? project.title : project.title[language];
        return (
          <article className="other-row" key={project.id}>
            <div className="other-info">
              <div className="other-heading">
                <h3 className="other-name">{title}</h3>
                {project.status && (
                  <span className={`other-badge ${project.status.type}`}>
                    {project.status[language]}
                  </span>
                )}
              </div>
              <p className="other-description">{project.description[language]}</p>
              <div className="other-tags">
                {project.tags.map((tag, i) => {
                  const TagIcon = getTechIcon(tag);
                  return (
                    <span className="tech-tag" key={i}>
                      {TagIcon && <TagIcon />}
                      {tag}
                    </span>
                  );
                })}
              </div>
            </div>
            <a
              className="other-repo"
              href={project.repo}
              target="_blank"
              rel="noopener noreferrer"
              aria-label={
                language === 'es'
                  ? `${title} - repositorio`
                  : `${title} - repository`
              }
            >
              <svg viewBox="0 0 24 24" fill="currentColor" aria-hidden="true">
                <path d="M12 .5C5.65.5.5 5.65.5 12c0 5.08 3.29 9.39 7.86 10.91.58.11.79-.25.79-.55v-2.15c-3.2.7-3.87-1.36-3.87-1.36-.52-1.33-1.28-1.69-1.28-1.69-1.05-.72.08-.7.08-.7 1.16.08 1.77 1.19 1.77 1.19 1.03 1.76 2.7 1.25 3.35.96.1-.75.4-1.25.73-1.54-2.55-.29-5.24-1.28-5.24-5.68 0-1.26.45-2.29 1.19-3.09-.12-.29-.52-1.46.11-3.05 0 0 .97-.31 3.18 1.18a11 11 0 0 1 5.79 0c2.2-1.49 3.17-1.18 3.17-1.18.63 1.59.23 2.76.11 3.05.74.8 1.19 1.83 1.19 3.09 0 4.41-2.69 5.38-5.26 5.66.41.36.77 1.06.77 2.14v3.17c0 .31.21.67.8.55A11.5 11.5 0 0 0 23.5 12C23.5 5.65 18.35.5 12 .5z" />
              </svg>
            </a>
          </article>
        );
      })}
    </div>
  </section>
);

export default ProjectsList;